title: leandronagata.com.br
author: L.Nagata
email: contato@leandronagata.com.br

domain: macleod85.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://macleod85.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /REPOSITORY-NAME/      # place folder name if the site is served in a subfolder

description: > # this means to ignore newlines until "baseurl:"
  Official site made with Jekyll
  # Write an awesome description for your new site here. You can edit this
  # line in _config.yml. It will appear in your document head meta (for
  # Google search results) and in your feed.xml site description.
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima